services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-todo}
      POSTGRES_USER: ${POSTGRES_USER:-todo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-todo}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devops-net

  app:
    image: tg/todo-app:${APP_TAG:-latest}
    container_name: todo-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-todo}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-todo}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-todo}
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - devops-net

volumes:
  pgdata:

networks:
  devops-net:
    driver: bridge
